# -*- coding: utf-8 -*-
"""Editor de Imagens em Lotes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlzrLeZRgHWLXwWru0XXy_MHr9b4dpba

TRABALHO FINAL DE PYTHON

Tema:
Editor de Imagens em Lote

Integrantes:
Ramon Camilo Figueiredo
Murilo Eusébio Cortez
Giovane Bonache Abrantes

Bibliotecas utilizadas:
- OpenCV
- NumPy
- Matplotlib
- ZipFile

Descrição:
Sistema capaz de receber várias imagens, pedir o filtro a ser utilizado
e aplica-los automaticamente e gerar
um pacote para download.""
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
from zipfile import ZipFile
import os

uploaded = files.upload()

os.makedirs("resultado", exist_ok=True)

print("\nFILTROS DISPONÍVEIS:")
print("1 - Escala de Cinza")
print("2 - Bordas (Canny)")
print("3 - Blur")
print("4 - Alto Contraste")
print("5 - Negativo")
print("6 - Sharpen (Nitidez)")

opcao = input("\nEscolha o filtro (1-6): ")

for nome_arquivo in uploaded.keys():

    imagem = cv2.imread(nome_arquivo)

    imagem_rgb = cv2.cvtColor(
        imagem,
        cv2.COLOR_BGR2RGB
    )

    resultado = None
    nome_filtro = ""

    if opcao == "1":

        resultado = cv2.cvtColor(
            imagem,
            cv2.COLOR_BGR2GRAY
        )

        nome_filtro = "cinza"

    elif opcao == "2":

        cinza = cv2.cvtColor(
            imagem,
            cv2.COLOR_BGR2GRAY
        )

        blur = cv2.GaussianBlur(
            cinza,
            (3,3),
            0
        )

        resultado = cv2.Canny(
            blur,
            30,
            100
        )

        nome_filtro = "bordas"

    elif opcao == "3":

        resultado = cv2.GaussianBlur(
            imagem_rgb,
            (11,11),
            0
        )

        nome_filtro = "blur"

    elif opcao == "4":

        cinza = cv2.cvtColor(
            imagem,
            cv2.COLOR_BGR2GRAY
        )

        resultado = cv2.equalizeHist(
            cinza
        )

        nome_filtro = "contraste"

    # FILTRO 5
    elif opcao == "5":

        resultado = cv2.bitwise_not(
            imagem_rgb
        )

        nome_filtro = "negativo"

    elif opcao == "6":

        kernel = np.array([
            [0,-1,0],
            [-1,5,-1],
            [0,-1,0]
        ])

        resultado = cv2.filter2D(
            imagem_rgb,
            -1,
            kernel
        )

        nome_filtro = "nitidez"

    else:

        print("Opção inválida.")
        break

    plt.figure(figsize=(10,5))

    plt.subplot(1,2,1)
    plt.imshow(
        cv2.resize(
            imagem_rgb,
            (400,400)
        )
    )
    plt.title("Original")
    plt.axis("off")

    plt.subplot(1,2,2)

    if len(resultado.shape) == 2:
        plt.imshow(
            cv2.resize(
                resultado,
                (400,400)
            ),
            cmap="gray"
        )
    else:
        plt.imshow(
            cv2.resize(
                resultado,
                (400,400)
            )
        )

    plt.title("Processada")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

    novo_nome = (
        "resultado/" +
        nome_arquivo.split(".")[0] +
        "_" +
        nome_filtro +
        ".jpg"
    )

    cv2.imwrite(
        novo_nome,
        resultado
    )

with ZipFile(
    "imagens_processadas.zip",
    "w"
) as zipf:

    for arquivo in os.listdir("resultado"):

        zipf.write(
            os.path.join(
                "resultado",
                arquivo
            )
        )

print("\nZIP criado com sucesso!")

files.download(
    "imagens_processadas.zip"
)